
version: '2'
services:
  genKeyPair_doris:
    image: dorissschoi/genkeypair
    hostname: genKeyPair_doris
    container_name: genkeypair_doris    
    ports:
      - 8042:1337
      - 8043:8080
    volumes:
      - ${COMPOSEROOT}/genKeyPair/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - ${COMPOSEROOT}/genKeyPair/config/env/development.coffee:/usr/src/app/config/env/production.coffee
      - ${COMPOSEROOT}/genKeyPair/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - ${COMPOSEROOT}/genKeyPair/www/js/config/development.coffee:/usr/src/app/www/js/config/production.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - ${COMPOSEROOT}/genKeyPair/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/genKeyPair:/usr/src/app
      
      
    env_file:
      - ./.env
    external_links:
      - todoactiviti_mongo
    networks:
      - todoactivitimongo_default
    entrypoint: top -b -d 1000          

networks:
  todoactivitimongo_default:
    external: true       