version: '2'
services:
  pki_mongo:
    image: mongo
    ports:
      - 27017
    command: mongod --directoryperdb

  pki:
    depends_on:
      - pki_mongo
    image: ewnchui/genkeypair
    ports:
      - 1337
    env_file:
      - ../.env
      - ./.env
    entrypoint: top -b -d 1000          
